project_name: fargate

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    id: "fargate"
    # Custom ldflags templates.
    # Default is `-s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{.Date}} -X main.builtBy=goreleaser`.
    ldflags:
      - -s -w -X gitlab.com/gitlab-org/ci-cd/custom-executor-drivers/fargate.VERSION={{ .Version }} -X gitlab.com/gitlab-org/ci-cd/custom-executor-drivers/fargate.REVISION={{.Commit}} -X gitlab.com/gitlab-org/ci-cd/custom-executor-drivers/fargate.BRANCH={{.Branch}} -X gitlab.com/gitlab-org/ci-cd/custom-executor-drivers/fargate.BUILT={{.Date}}
    main: ./cmd/fargate
    binary: "{{ .ProjectName }}"
